// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
import 'package:flutter/material.dart';
import 'package:iconsax/iconsax.dart';

class MinyIcons {
  static const IconData cross = Icons.close_rounded;
  static const IconData fillScan = Iconsax.scan5;
  static const IconData filter = Iconsax.setting_4;
  static const IconData outlineArrowUp = Iconsax.arrow_up_2;
  static const IconData outlineReceiveMoney = Iconsax.card_receive;
  static const IconData outlineSendMoney = Iconsax.card_send;
  static const IconData plus = Icons.add_rounded;
}
