// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
class BorderWidthTokens {
  static const double none = 0.0;
  static const double small = 1.0;
  static const double medium = 2.0;
  static const double large = 4.0;
}
