// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
class BorderRadiusTokens {
  static const double none = 0.0;
  static const double xxSmall = 2.0;
  static const double xSmall = 4.0;
  static const double small = 8.0;
  static const double normal = 12.0;
  static const double medium = 16.0;
  static const double large = 20.0;
  static const double xLarge = 24.0;
}
