// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
import 'package:flutter/material.dart';

class ColorTokens {
  static const Color primary = Color(0xFF00CD7E);
  static const Color primaryDark = Color(0xFF008653);
  static const Color secondary = Color(0xFFFA5A2A);
  static const Color secondaryDark = Color(0xFFDE3300);
  static const Color contrastDark = Color(0xFF535B66);
  static const Color contrastMedium = Color(0xFF86898D);
  static const Color contrastLow = Color(0xFFE0E0E0);
  static const Color contrastLight = Color(0xFFF4F4F4);
  static const Color dark = Color(0xFF000000);
  static const Color light = Color(0xFFFFFFFF);
  static const Color shadow = Color(0xFFBFBFBF);
}
