// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
import 'package:flutter/material.dart';
import 'color_tokens.dart';

class ElevationTokens {
  static const BoxShadow e1 = BoxShadow(
    color: ColorTokens.shadow,
    offset: Offset(0.0, 1.0),
    blurRadius: 10.0,
  );
}
