// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
class OpacityTokens {
  static const double o4 = 0.04;
  static const double o5 = 0.05;
  static const double o8 = 0.08;
  static const double o11 = 0.11;
  static const double o12 = 0.12;
  static const double o14 = 0.14;
  static const double o24 = 0.24;
  static const double o38 = 0.38;
  static const double o40 = 0.4;
  static const double o48 = 0.48;
  static const double o60 = 0.6;
  static const double o72 = 0.72;
}
