// DO NOT EDIT THIS FILE. THIS FILE IS USED BY DESIGN SYSTEMS.
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class TypographyTokens {
  static TextStyle titleRegular = TextStyle(
    fontFamily: 'Inter',
    fontSize: 22.0.sp,
    fontWeight: FontWeight.w700,
  );
  static TextStyle titleBold = TextStyle(
    fontFamily: 'Inter',
    fontSize: 22.0.sp,
    fontWeight: FontWeight.w900,
  );
  static TextStyle headingSmallRegular = TextStyle(
    fontFamily: 'Inter',
    fontSize: 18.0.sp,
    fontWeight: FontWeight.w600,
  );
  static TextStyle headingSmallMedium = TextStyle(
    fontFamily: 'Inter',
    fontSize: 18.0.sp,
    fontWeight: FontWeight.w700,
  );
  static TextStyle headingLargeBold = TextStyle(
    fontFamily: 'Inter',
    fontSize: 20.0.sp,
    fontWeight: FontWeight.w800,
  );
  static TextStyle labelRegular = TextStyle(
    fontFamily: 'Inter',
    fontSize: 16.0.sp,
    fontWeight: FontWeight.w700,
  );
  static TextStyle labelBold = TextStyle(
    fontFamily: 'Inter',
    fontSize: 16.0.sp,
    fontWeight: FontWeight.w800,
  );
  static TextStyle bodyRegular = TextStyle(
    fontFamily: 'Inter',
    fontSize: 15.0.sp,
    fontWeight: FontWeight.w500,
  );
  static TextStyle bodyBold = TextStyle(
    fontFamily: 'Inter',
    fontSize: 15.0.sp,
    fontWeight: FontWeight.w800,
  );
  static TextStyle caption = TextStyle(
    fontFamily: 'Inter',
    fontSize: 12.0.sp,
    fontWeight: FontWeight.w500,
  );
  static TextStyle quote = TextStyle(
    fontFamily: 'Inter',
    fontSize: 10.0.sp,
    fontWeight: FontWeight.w700,
  );
}
