// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: ProdFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'ProdFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ3zPxwVcCtTBdlsBbxdA-lV48BVA8X5s',
    appId: '1:507101009122:web:235748f5d303f03c44babb',
    messagingSenderId: '507101009122',
    projectId: 'tacklepay-prod',
    authDomain: 'tacklepay-prod.firebaseapp.com',
    storageBucket: 'tacklepay-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALXt7BudkiCu8NUIahHAQjBGcNjKHxnmM',
    appId: '1:507101009122:android:aec23060849abb7c44babb',
    messagingSenderId: '507101009122',
    projectId: 'tacklepay-prod',
    storageBucket: 'tacklepay-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_iW_BC_ooiy5Mcl0PFBuR1gcfHK6Yl6o',
    appId: '1:507101009122:ios:eaa5a26f75b0766044babb',
    messagingSenderId: '507101009122',
    projectId: 'tacklepay-prod',
    storageBucket: 'tacklepay-prod.firebasestorage.app',
    iosBundleId: 'com.blackminystudio.tacklepay',
  );
}
