// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: StagingFirebaseOptions.currentPlatform,
/// );
/// ```
class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'StagingFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'StagingFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'StagingFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'StagingFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnstFwxocv-7XxoJNL0Pu-7qT7qkivyec',
    appId: '1:866511156331:web:f06b7bec28e8d83df4ed2e',
    messagingSenderId: '866511156331',
    projectId: 'tacklepay-staging',
    authDomain: 'tacklepay-staging.firebaseapp.com',
    storageBucket: 'tacklepay-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-rmP3ozMETtogvvy5HP-_NgGjY6n74yo',
    appId: '1:866511156331:android:d2ab5abe2ebfb0b4f4ed2e',
    messagingSenderId: '866511156331',
    projectId: 'tacklepay-staging',
    storageBucket: 'tacklepay-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcflyGOhPm6I_R1WGm9XLFF-fTNPjQpH0',
    appId: '1:866511156331:ios:528c1d875c60fd5bf4ed2e',
    messagingSenderId: '866511156331',
    projectId: 'tacklepay-staging',
    storageBucket: 'tacklepay-staging.firebasestorage.app',
    iosBundleId: 'com.blackminystudio.tacklepaystaging',
  );
}
