// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DevFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwvavRZGtp3pHQreQxvnBkCRoz3_5Yg8A',
    appId: '1:911090474857:web:0a29ac106093d892a9e7f8',
    messagingSenderId: '911090474857',
    projectId: 'tacklepay-dev',
    authDomain: 'tacklepay-dev.firebaseapp.com',
    storageBucket: 'tacklepay-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQUss85fygRo2G2bdiahvh2VmHbX13Em8',
    appId: '1:911090474857:android:d128aa5f85c4c126a9e7f8',
    messagingSenderId: '911090474857',
    projectId: 'tacklepay-dev',
    storageBucket: 'tacklepay-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTjVXj0QISn6PY1gb9yvh6sCzctAH1nFk',
    appId: '1:911090474857:ios:35f810b6666b91c0a9e7f8',
    messagingSenderId: '911090474857',
    projectId: 'tacklepay-dev',
    storageBucket: 'tacklepay-dev.firebasestorage.app',
    iosBundleId: 'com.blackminystudio.tacklepaydev',
  );
}
